---

- name: assert that mandatory variables are defined
  assert:
    that:
      - influxdbproxy_telegraf_output_influxdbv2 is defined
    fail_msg: 'mandatory variable(s) not defined'

- name: include telegraf tasks for debian
  include_tasks: debian.yml
  args:
    apply:
      become: yes
  when:
    - ansible_distribution == 'Debian'

